### ISSUE TITLE
vfkit exited unexpectedly with exit code 2

### ISSUE THREAD

**Issue by ericcurtin** [containers/krunkit#13]
Followed https://sinrega.org/2024-03-06-enabling-containers-gpu-macos/, got as far as:

```
$ cat ~/.config/containers/containers.conf
[containers]

[engine]
  active_service = "podman-machine-default-root"
  [engine.service_destinations]
    [engine.service_destinations.podman-machine-default]
      uri = "ssh://core@localhost:50181/run/user/501/podman/podman.sock"
      identity = "/Users/ecurtin/.ssh/podman-machine-default"
    [engine.service_destinations.podman-machine-default-root]
      uri = "ssh://root@localhost:50181/run/podman/podman.sock"
      identity = "/Users/ecurtin/.ssh/podman-machine-default"

[machine]
  provider = "applehv"

[network]

[secrets]

[configmaps]

[farms]
$ ls -ltr /opt/homebrew/Cellar/podman/5.1.2/libexec/podman/
total 54544
-rwxr-xr-x  1 ecurtin  admin  16930064 Jul 10 13:20 vfkit.bak
-rwxr-xr-x  1 ecurtin  admin  10991010 Jul 10 13:20 gvproxy
lrwxr-xr-x  1 ecurtin  admin        25 Jul 11 12:12 vfkit -> /opt/homebrew/bin/krunkit
$ ls -ltr /opt/homebrew/bin/krunkit
lrwxr-xr-x  1 ecurtin  admin  35 Jul 11 12:11 /opt/homebrew/bin/krunkit -> ../Cellar/krunkit/0.1.1/bin/krunkit
$ ls -ltr /opt/homebrew/Cellar/krunkit/0.1.1/bin/krunkit
-r-xr-xr-x  1 ecurtin  admin  1223456 Jul 11 12:11 /opt/homebrew/Cellar/krunkit/0.1.1/bin/krunkit
$ podman machine start
Starting machine "podman-machine-default"
Error: vfkit exited unexpectedly with exit code 2
$ podman machine stop
Machine "podman-machine-default" stopped successfully
$ podman machine start
Starting machine "podman-machine-default"
WARN[0000] detected port conflict on machine ssh port [59282], reassigning
Error: vfkit exited unexpectedly with exit code 2
```

**Comment by slp** [comment]
The info in that post is a bit old. `krunkit` is now directly supported as a provider in podman 5.1.

To enable it, just put this in `~/.config/containers/containers.conf`:

```
[machine]
  provider = "libkrun"
```

After that, `podman machine init` and `podman machine start` should get you a working VM.

**Comment by ericcurtin** [comment]
Thanks, that worked, well the GPU passthrough doesn't seem to be working but it boots with 4 cores, etc. ☺️

**Comment by tylerfanelli** [comment]
Hi @ericcurtin, I'm curious why GPU passthrough isn't working. Are there any logs you can show?

**Comment by ericcurtin** [comment]
When I run vulkaninfo:

```
Devices:
========
GPU0:
	apiVersion         = 1.2.0
	driverVersion      = 23.3.5
	vendorID           = 0x106b
	deviceID           = 0xe0303ef
	deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName         = Virtio-GPU Venus (Apple M1)
	driverID           = DRIVER_ID_MESA_VENUS
	driverName         = venus
	driverInfo         = Mesa 23.3.5
	conformanceVersion = 1.3.0.0
	deviceUUID         = 94441f32-25fb-7d10-f7e9-e0a7bfbb7263
	driverUUID         = d2076857-3352-aaf9-a5ba-778bcb213a61
GPU1:
	apiVersion         = 1.3.267
	driverVersion      = 0.0.1
	vendorID           = 0x10005
	deviceID           = 0x0000
	deviceType         = PHYSICAL_DEVICE_TYPE_CPU
	deviceName         = llvmpipe (LLVM 17.0.6, 128 bits)
	driverID           = DRIVER_ID_MESA_LLVMPIPE
	driverName         = llvmpipe
	driverInfo         = Mesa 23.3.5 (LLVM 17.0.6)
	conformanceVersion = 1.3.1.1
	deviceUUID         = 6d657361-3233-2e33-2e35-000000000000
	driverUUID         = 6c6c766d-7069-7065-5555-494400000000
```

it looks reasonably ok. But when I actually run a workload "nvtop" from macOS shows everything in CPU driven, rather than GPU driver.

Question is @slp 's patched Mesa still required? Or could I use something like Fedora 41 Mesa?

**Comment by ericcurtin** [comment]
Actually nevermind... It's my reading of nvtop output that's wrong, this may actually be an nvtop bug or unimplemented stuff... All the processes read 0% GPU usage in nvtop with plenty of CPU usage... But overall GPU usage is high when things are running...

**Comment by slp** [comment]
The patched mesa is still required. The way I use to confirm it's using the GPU is checking the `GPU History` window of `Activity Monitor`.

**Comment by ericcurtin** [comment]
I wonder what's a heuristic for setting this value also:

"
  -ngl N, --n-gpu-layers N
                        number of layers to store in VRAM
"

it makes a significant difference as you know :)

**Comment by ericcurtin** [comment]
Maybe something past maximum like 99 makes, sense because on Apple GPU it caps out at 33

**Comment by slp** [comment]
IIRC, `-1` means auto, kinda.

**Comment by ericcurtin** [comment]
I get 0 GPU usage and  this in output when I do -1:

```
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/33 layers to GPU
```

**Comment by ericcurtin** [comment]
I notice this works for Intel integrated graphics too, but its waaaaaaaaaaaaaay slower than Intel CPU, VRAM is probably so small it's not worth it anyway I guess...

**Comment by ericcurtin** [comment]
Closing anyway, thanks for the help!
