### ISSUE TITLE
[BUG]: Unable to start when memory exceeds 27647

### ISSUE THREAD

**Issue by BlackHole1** [containers/krunkit#17]
After testing, when the `--memory` value is greater than **27647**, krun will fail to start. The error is as follows:

```txt
Error: unable to begin running krun workload
```

**Comment by BlackHole1** [comment]
`(27647 + 1) * 1024 * 1024 = 28,991,029,248`

![Image](https://github.com/user-attachments/assets/a85964a3-62fb-4456-8b5f-d2ac9e2dde28)

Memory max value is 27 GiB. Is this expected?

**Comment by tylerfanelli** [comment]
This is dependent on the system you're running on, no? 27GiB of RAM is no small amount. How much RAM is on the system you're running with?

**Comment by BlackHole1** [comment]
@tylerfanelli Sorry. I forgot to add my system information.

System: Darwin Arm64 (M3)
Memory: 36GB

![Image](https://github.com/user-attachments/assets/6dea1ced-8d34-45a5-aac7-2dd8fb165226)

**Comment by slp** [comment]
Works fine here with arbitrarily large memory sizes, even larger than the host's RAM (the memory for the guest is not preallocated). Could you please build krunkit with #18 and re-run your test with `--krun-log-level 5`?

**Comment by BlackHole1** [comment]
@slp I am not very familiar with Rust, and when I run the make command, I get the following error. What should I do?

```txt
  = note: ld: library 'krun-efi' not found
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: could not compile `krunkit` (bin "krunkit") due to 1 previous error
make: *** [target/release/krunkit] Error 101
```

**Comment by BlackHole1** [comment]
I found that orbstack also encountered a similar issue, but since it is closed-source software, I am not sure how it was fixed: https://github.com/orbstack/orbstack/issues/1178

**Comment by BlackHole1** [comment]
I added some logs to [libkrun/hvf/src/lib.rs#L201](https://github.com/containers/libkrun/blob/88ac85eccab9e56e38967c10db07f93c4652fb6c/src/hvf/src/lib.rs#L201) and found that the return value of `hv_vm_map` is: `HV_BAD_ARGUMENT`.

![Image](https://github.com/user-attachments/assets/107e102a-e7b7-4fe6-aa5b-4f84b7aaad8a)

HV_BAD_ARGUMENT: https://developer.apple.com/documentation/hypervisor/1585168-hypervisor_errors/hv_bad_argument

**Comment by BlackHole1** [comment]
Relevant discussion:
* https://github.com/utmapp/UTM/issues/5537
* https://github.com/containers/podman/discussions/19528

**Comment by slp** [comment]
Could you please give #19 a try? I think it should work with arbitrary memory configurations, even ones exceeding the memory available on the host (with the upper bound of 60 GiB).

**Comment by BlackHole1** [comment]
@slp It worked! Thanks!
