### ISSUE TITLE
Needs a MAC installation procedure as part of the release, so people can directly install it from github.

### ISSUE THREAD

**Issue by rhatdan** [containers/krunkit#7]

**Comment by tylerfanelli** [comment]
How would this work dependencies? At the moment, this relies on `libkrun-efi` and `virglrenderer`. On macOS, we can specify these dependencies with brew (instructions in README). For a github installation, would we need to include dependencies for installation as well?

**Comment by rhatdan** [comment]
I don't know but I would figure you suck them into your installation procedure. IE You have to package them up.

@lsm5 @ashley-cui  you probably know better then me.

**Comment by lsm5** [comment]
> I don't know but I would figure you suck them into your installation procedure. IE You have to package them up.
> 
> @lsm5 @ashley-cui you probably know better then me.

macos is all @ashley-cui

**Comment by ashley-cui** [comment]
Easiest way for us to do it on Mac is to maintain our own brew repo, called a brew tap. It looks like we already do that on the readme.
